// src/pages/an-tu-thuoc-linh/khao-sat.tsx
import React, { useEffect, useState } from 'react';

import { Box, Button, CircularProgress, Dialog, DialogTitle } from '@mui/material';
import ErrorIcon from '@mui/icons-material/Error';

import GiftQuestion from '../../components/GiftQuestion';
import { useDispatch, useSelector } from 'react-redux';
import { getGiftQuestions, updateGiftQuestion, updateGiftQuestions } from '../../slices/gift.slice';
import { giftQuestions } from '../../constant';

const GiftAssessment: React.FC = () => {
  const [currentPage, setCurrentPage] = useState(1);
  const [showErrorDialog, setShowErrorDialog] = useState(false);
  const [isSubmit, setIsSubmit] = useState(false);

  const dispatch = useDispatch();
  const questions = useSelector(getGiftQuestions);

  const totalPerPage = 10;
  const totalPages = Math.ceil(giftQuestions.length / totalPerPage);

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [currentPage]);

  useEffect(() => {
    const defaultQuestions = JSON.parse(localStorage.getItem('giftQuestions') || 'null');

    if (defaultQuestions) {
      console.log(defaultQuestions);
      dispatch(updateGiftQuestions(defaultQuestions));
    }
  }, []);

  const onClickPrev = () => {
    setCurrentPage(currentPage - 1);
  };

  const onClickNext = () => {
    setIsSubmit(false);

    let hasError = false;
    let result: any = {};
    Object.values(questions)
      .slice((currentPage - 1) * totalPerPage, currentPage * totalPerPage)
      .forEach((question: any) => {
        if (!question.value) {
          hasError = true;
          dispatch(
            updateGiftQuestion({
              id: question.id,
              question: { hasError: true }
            })
          );
          result[question.id] = { type: question.type, mark: 0 };
        } else {
          result[question.id] = { type: question.type, mark: question.value };
        }
      });

    if (!hasError) {
      setCurrentPage(currentPage + 1);
    } else {
      setShowErrorDialog(true);
    }
  };

  const onClickSubmit = () => {
    setIsSubmit(true);

    let hasError = false;
    let result: any = {};
    Object.values(questions).forEach((question: any) => {
      if (!question.value) {
        hasError = true;
        dispatch(updateGiftQuestion({ id: question.id, question: { hasError: true } }));
        result[question.id] = { type: question.type, mark: 0 };
      } else {
        result[question.id] = { type: question.type, mark: question.value };
      }
    });

    if (!hasError) {
      localStorage.setItem('giftQuestions', JSON.stringify(questions));
      localStorage.setItem('giftResultV2', JSON.stringify(result));

      window.open('/an-tu-thuoc-linh', '_self');
    } else {
      setShowErrorDialog(true);
      setIsSubmit(false);
    }
  };

  return (
    <div className='p-2 sm:p-3 md:p-4 lg:p-5 flex flex-col items-center bg-blue-200' style={{ minHeight: '100vh' }}>
      <div className='w-full md:w-3/4 lg:w-2/3 mb-3 border-gray-400 rounded-lg bg-white'>
        <Box
          className='text-2xl md:text-3xl text-center text-white rounded-t-lg border-green-100 py-3 w-full'
          sx={{ bgcolor: 'primary.main' }}
        >
          Ân tứ thuộc linh
        </Box>
        <div className='p-2 md:p-3 lg:p-4 text-sm'>
          Hãy trả lời {giftQuestions.length} câu hỏi (5 nhóm) bằng cách chấm mức độ đúng với khả năng/xu hướng/tâm tình
          của bạn. Đúng nhất với mình là điểm 10, không đúng nhất với mình là điểm 1. Chấm điểm ngay cho các câu mô tả
          được đưa ra. Đừng suy nghĩ cẩn thận quá, đây là chỉ là khảo sát.
        </div>
      </div>

      {Object.values(questions)
        .slice((currentPage - 1) * totalPerPage, currentPage * totalPerPage)
        .map((question: any) => (
          <GiftQuestion index={question.id as number} key={question.id} question={question} />
        ))}

      <div className='w-full md:w-3/4 lg:w-2/3 mb-3 border-gray-400 rounded-lg'>
        {currentPage === 1 && (
          <Button variant='contained' onClick={onClickNext}>
            Next
          </Button>
        )}

        {currentPage > 1 && currentPage < totalPages && (
          <Box>
            <Button variant='contained' onClick={onClickPrev} sx={{ height: 35, minWidth: 60 }}>
              Prev
            </Button>
            <Button variant='contained' onClick={onClickNext} style={{ marginLeft: 10, height: 35, minWidth: 60 }}>
              Next
            </Button>
          </Box>
        )}

        {currentPage === totalPages && (
          <Box>
            <Button variant='contained' onClick={onClickPrev} sx={{ height: 35, minWidth: 60 }}>
              Prev
            </Button>
            <>
              {isSubmit && (
                <Button variant='contained' style={{ marginLeft: 15, height: 35, minWidth: 90 }}>
                  <CircularProgress sx={{ color: '#fff' }} size={25} />
                </Button>
              )}

              {!isSubmit && (
                <Button
                  variant='contained'
                  onClick={onClickSubmit}
                  style={{ marginLeft: 15, height: 35, minWidth: 90 }}
                >
                  Submit
                </Button>
              )}
            </>
          </Box>
        )}
      </div>

      <Dialog onClose={() => setShowErrorDialog(false)} open={showErrorDialog} sx={{ top: -400 }}>
        <DialogTitle className='text-md text-red-600'>
          <ErrorIcon className='mr-2' />
          <span>Hãy trả lời tất cả câu hỏi nào!</span>
        </DialogTitle>
      </Dialog>
    </div>
  );
};

export default GiftAssessment;

// pages/an-tu-thuoc-linh/khao-sat.vue
<template>
  <div>
    <QuestionBar v-bind:tab-question-type="tabQuestionType"/>

    <div class="flex flex-col content-center items-center p-2 md:p-4">
      <div class="text-center text-3xl p-2 md:p-3 lg:p-4 my-3 border-gray-400 rounded-lg bg-white w-full md:w-3/4 lg:w-2/3">Bài khảo sát ân tứ thuộc linh</div>

      <div v-for="(question, qIndex) in questions" :key="question.id"
           class="p-2 md:p-3 lg:p-4 mb-3 border-gray-400 rounded-lg bg-white w-full md:w-3/4 lg:w-2/3">
        <div>
          <strong>Câu {{ question.id }}:</strong>
          <span class="ml-2 cursor-pointer">{{ question.text }}</span>
        </div>
        <star-rating :animate="true" :rtl="false" :increment="1"
                     :max-rating="10" :rating="question.mark || 0"
                     @rating-selected="setRating(qIndex, $event)"></star-rating>
      </div>

      <div class="flex justify-center">
        <t-button class="mt-3" v-on:click="submit()">Gửi kết quả</t-button>
      </div>
    </div>
  </div>
</template>

<style lang="scss">
.vue-star-rating-pointer {
  padding: 0;
  margin: 0;
}

.vue-star-rating-star {
  @media only screen and (min-width: 200px) {
    height: 25px;
    width: 25px;
  }

  @media only screen and (min-width: 600px) {
    height: 40px;
    width: 40px;
  }
}
</style>

<script>
import StarRating from 'vue-star-rating';

import QuestionBar from '../../components/QuestionBar';
import { TabQuestionType, UPDATE_GIFT_QUESTIONS, UPDATE_GIFT_RESULT } from '../../store';

export default {
  components: { QuestionBar, StarRating },
  data() {
    return {
      errorQuestionIds: {},
      tabQuestionType: TabQuestionType.Gift
    };
  },
  computed: {
    questions: function () {
      return this.$store.getters.giftQuestions;
    }
  },
  methods: {
    setRating(qIndex, rating) {
      const _questions = JSON.parse(JSON.stringify(this.questions));

      const isValid = rating > 0 && rating <= 10;

      this.errorQuestionIds = { qIndex: isValid };

      _questions[qIndex].mark = rating;
      _questions[qIndex].error = !isValid;

      this.$store.dispatch(UPDATE_GIFT_QUESTIONS, _questions);
    },
    submit() {
      let hasError = false;
      const questionMarkGroups = this.questions.reduce((acc, question) => {
        if (question.mark <= 0 || question.mark > 10) {
          hasError = true;
        }
        acc[question.type] = {
          type: question.type,
          mark: (acc[question.type]?.mark || 0) + (question.mark || 0)
        };
        return acc;
      }, []);

      if (hasError) {
        this.$dialog.alert({
          variant: 'error',
          title: '',
          text: 'Điểm của bạn chưa hợp lệ!',
          icon: ''
        }).then((result) => {
          console.log(result);
        });
      } else {
        localStorage.setItem('giftResult', JSON.stringify(questionMarkGroups));
        localStorage.setItem('giftQuestions', JSON.stringify(this.questions));
        this.$store.dispatch(UPDATE_GIFT_RESULT, questionMarkGroups);

        window.open('/an-tu-thuoc-linh', '_self');
      }
    }
  },
  mounted() {
    const questions = localStorage.getItem('giftQuestions');
    if (questions) {
      this.$store.dispatch(UPDATE_GIFT_QUESTIONS, JSON.parse(questions));
    }
  }
};
</script>
